### PR TITLE
fix https://github.com/roogle-rs/roogle/issues/18

### LINKED ISSUE #5: missing brackets leads to interesting results
(Loving your work btw)

`fn (PathBuf) -> String` returns sensible results.

`fn PathBuf -> String` returns _interesting_ results. I was just wondering if the prompt should be `fn ` given that it has to be typed often and whether `(` `)` are needed for simple cases.

### PR DESCRIPTION
**Pull request by asukaminato0721**
If I understand the parser correctly,

it doesn't support

```
type -> type
```

the bracket is necessary. As #5 said.

so I just change to `multispace0`.

the result:

```sh
curl -X GET \
  -d "fn(Option<Result<T, E>>) -> Result<Option<T>, E>>" \
                                         "localhost:8000/search?scope=set:libstd"
[{"name":"transpose","path":["core","option","Option","transpose"],"link":["core","option","enum.Option.html#method.transpose"],"docs":"Transposes an `Option` of a [`Result`] into a [`Result`] of an `Option`.\n\n[`None`] will be mapped to <code>[Ok]\\([None])</code>.\n<code>[Some]\\([Ok]\\(\\_))
```

and

```sh
curl -X GET \
 -d "fn (Option<Result<T, E>>) -> Result<Option<T>, E>>" \
                                         "localhost:8000/search?scope=set:libstd"
[{"name":"transpose","path":["core","option","Option","transpose"],"link":["core","option","enum.Option.html#method.transpose"],"docs":"Transposes an `Option` of a [`Result`] into a [`Result`] of an `Option`.\n\n[`None`] will be mapped to <code>[Ok]\\([None])</code>.\n<code>[Some]\\([Ok]\\(\\_))</code> 
```

so it seems work properly.

---

to fix the

```
fn(xx)
vs
fn f(xx)
```

I let the space before `f`, instead of after `fn`.

---

to fix #5, I guess add a `alt` may help.

or something like `delimited( opt( char('(') ), xx ,  opt( char(')') )  )`

### CODE REVIEW

**Comment by asukaminato0721** [comment]
this may have problem with `fn f(xx) -> xx`

but I found the original behavior is strange though, as #20 said.

File: roogle-engine/src/query/parse.rs [hunk 1]
```diff
@@ -2,7 +2,7 @@ use nom::{
     branch::alt,
     bytes::complete::{tag, take_while1},
     character::complete::char,
-    character::complete::{alpha1, alphanumeric1, multispace0, multispace1},
```
Comment (hkmatsumoto) [inline roogle-engine/src/query/parse.rs:5]: CI seems to fail due to this removal of `multispace1` while using the function at L43.

**Comment by asukaminato0721** [comment]
@hkmatsumoto now it should work.

**Review by hkmatsumoto — APPROVED** [review]
LGTM, thanks!
